package template

var MakefileOptions struct {
	Protos []string
}

const Makefile = `# Generated by protoc-gen-client
.PHONY: default
default: generate

.PHONY: generate
generate:
        mkdir -p gen
        protoc --go_out=gen {{ .Protos }}
`
